#!/bin/bash

if [[ -e "/home/versao" ]]; then
    rm "/home/versao"
fi

wget -P "/home" -q "https://raw.githubusercontent.com/modderajuda/donomodderajuda/main/versao"

if [[ -f "/home/versao" ]]; then
    vrs1=$(sed -n '1p' "/bin/versao" | sed -e 's/[^0-9]//ig')
    vrs2=$(sed -n '1p' "/home/versao" | sed -e 's/[^0-9]//ig')
    
    if [[ "$vrs1" != "$vrs2" ]]; then
        mv "/home/versao" "/tmp/att"
    fi
fi

echo "Script executado com sucesso."
